/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainjframe;

import api.ElementoExamen;
import api.Pregunta;
import api.Respuesta;
import api.Termino;
import com.google.common.base.Splitter;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;
import com.tinkerpop.blueprints.Vertex;
import conceptmanager.ConceptManager;
import conceptmanager.Concepto;
import conceptmanager.GraphViewer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import ortografia.LangTools;

/**
 *
 * @author Martin
 */
public class CorreccionWizard extends javax.swing.JFrame {

    Respuesta respuesta;
    GraphViewer gv;

    /**
     * Creates new form CorreccionWizard
     */
    public CorreccionWizard() {
        respuesta = new Respuesta();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tabPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSOUT = new javax.swing.JTextArea();
        btnValidar = new javax.swing.JButton();
        lstRespuestas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTexto1 = new javax.swing.JTextArea();
        btnDetectarConceptos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtConceptos = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTexto2 = new javax.swing.JTextArea();
        btnDividirConceptos = new javax.swing.JButton();
        btnDetectarRutas = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtLogRutas = new javax.swing.JTextArea();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Asistente de corrección");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Paso 1");

        jLabel2.setText("Ingresar el texto y evaluar si es correcto, ortográfica y sintácticamente");

        txtTexto.setColumns(20);
        txtTexto.setLineWrap(true);
        txtTexto.setRows(5);
        txtTexto.setText("El paradigma poo se basa en objetos que usan atributos y sus características son herencia y polimorfismo");
        txtTexto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtTexto);

        txtSOUT.setEditable(false);
        txtSOUT.setColumns(20);
        txtSOUT.setLineWrap(true);
        txtSOUT.setRows(5);
        jScrollPane2.setViewportView(txtSOUT);

        btnValidar.setText("Analizar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        lstRespuestas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "El paradigma poo se basa en objetos que usan atributos y sus características son herencia y polimorfismo", "El paradigma relacional utiliza tuplas que son conjuntos de atributos", "La lógica de primer orden utiliza nexos y proposiciones para modelar frases y oraciones", "Un paradigma es un modelo de diseño e implementación de programas" }));
        lstRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstRespuestasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lstRespuestas, 0, 556, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(lstRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("Paso 1", jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Paso 2");

        jLabel4.setText("El texto ingresado ya es correcto, detectar los CONCEPTOS existentes en la base de datos");

        txtTexto1.setEditable(false);
        txtTexto1.setBackground(new java.awt.Color(204, 204, 204));
        txtTexto1.setColumns(20);
        txtTexto1.setLineWrap(true);
        txtTexto1.setRows(5);
        txtTexto1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtTexto1);

        btnDetectarConceptos.setText("Detectar conceptos");
        btnDetectarConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectarConceptosActionPerformed(evt);
            }
        });

        txtConceptos.setEditable(false);
        txtConceptos.setColumns(20);
        txtConceptos.setLineWrap(true);
        txtConceptos.setRows(5);
        jScrollPane4.setViewportView(txtConceptos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDetectarConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetectarConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        tabPanel.addTab("Paso 2", jPanel2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Paso 3");

        jLabel6.setText("Detectar el primer concepto, usarlo como raiz del grafo y obtener las rutas que incluyan los otros conceptos.");

        txtTexto2.setEditable(false);
        txtTexto2.setBackground(new java.awt.Color(204, 204, 204));
        txtTexto2.setColumns(20);
        txtTexto2.setLineWrap(true);
        txtTexto2.setRows(5);
        txtTexto2.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtTexto2);

        btnDividirConceptos.setLabel("Dividir conceptos");
        btnDividirConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirConceptosActionPerformed(evt);
            }
        });

        btnDetectarRutas.setLabel("Detectar rutas y graficar");
        btnDetectarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectarRutasActionPerformed(evt);
            }
        });

        txtLogRutas.setEditable(false);
        txtLogRutas.setColumns(20);
        txtLogRutas.setLineWrap(true);
        txtLogRutas.setRows(5);
        txtLogRutas.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtLogRutas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnDividirConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetectarRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDividirConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetectarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("Paso 3", jPanel3);

        btnNext.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnNext.setText("Siguiente »");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnPrev.setText("« Anterior");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnValidarActionPerformed
    {//GEN-HEADEREND:event_btnValidarActionPerformed
        try {
            // respuesta es una propiedad de la clase, porque debo utilizarla
            // en distintos lugares
            // Se inicializa al analizar el texto
            respuesta = new Respuesta(txtTexto.getText());
            boolean seguir = ValidarTexto(respuesta);
            btnNext.setEnabled(seguir);
        } catch (IOException ex) {
            Logger.getLogger(ElementoExamen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNextActionPerformed
    {//GEN-HEADEREND:event_btnNextActionPerformed
        // Pasar a la siguiente pestaña
        tabPanel.setSelectedIndex(tabPanel.getSelectedIndex() + 1);
        boolean ultima_pagina = tabPanel.getSelectedIndex() == tabPanel.getTabCount() - 1;
        btnNext.setEnabled(!ultima_pagina);
        btnPrev.setEnabled(tabPanel.getSelectedIndex() > 0);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPrevActionPerformed
    {//GEN-HEADEREND:event_btnPrevActionPerformed
        // Pasar a la anterior pestaña
        tabPanel.setSelectedIndex(tabPanel.getSelectedIndex() - 1);
        boolean primera_pagina = tabPanel.getSelectedIndex() == 0;
        btnPrev.setEnabled(!primera_pagina);
        btnNext.setEnabled(tabPanel.getSelectedIndex() < tabPanel.getTabCount());
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnDetectarConceptosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDetectarConceptosActionPerformed
    {//GEN-HEADEREND:event_btnDetectarConceptosActionPerformed
        // Hacer una consulta a la base de Conceptos
        ConceptManager cm = new ConceptManager("remote:localhost/PPR", "admin", "admin");
        respuesta = cm.evaluarRespuesta(respuesta);
        // Recorrer todos los terminos y mostrar cada uno, con su tipo, en el campo
        txtConceptos.setText("");
        StringBuilder bld = new StringBuilder();
        bld.append(String.format("Cantidad de términos: %d\n", respuesta.getTerminos().size()));
        for (Termino t : respuesta.getTerminos()) {
            String item = String.format("%s - [%s]\n", t.getNombre(), t.getTipo());
            bld.append(item);
        }

        bld.append("\n------------ TERMINOS ------------\n");
        bld.append(respuesta.getTerminosAsString(false));
        bld.append("\n------------ VALOR ------------\n");
        bld.append(respuesta.getValuesAsString());

        txtConceptos.setText(bld.toString());
    }//GEN-LAST:event_btnDetectarConceptosActionPerformed

    private void btnDividirConceptosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDividirConceptosActionPerformed
    {//GEN-HEADEREND:event_btnDividirConceptosActionPerformed
        // Obtener el primer concepto
        String primer_concepto = respuesta.getPrimerConceptoAsString();
        // Obtener todos los conceptos secundarios
        ArrayList<String> otros_conceptos = respuesta.getConceptosSecundariosAsString();

        ConceptManager cm = new ConceptManager("remote:localhost/PPR", "admin", "admin");
        Concepto concepto_inicial = cm.getConceptoByName(respuesta.getPrimerConceptoAsString());
        txtLogRutas.setText(cm.buildRouteQuery(concepto_inicial, otros_conceptos));

        StringBuilder bld = new StringBuilder();
        bld.append(String.format("TEXTO ORIGINAL: %s\n", txtTexto.getText()));
        bld.append(String.format("CONCEPTO RAIZ: %s\n", primer_concepto));
        bld.append(String.format("CONCEPTOS SECUNDARIOS: %s\n", otros_conceptos.toString()));
        txtTexto2.setText(bld.toString());
    }//GEN-LAST:event_btnDividirConceptosActionPerformed

    private void btnDetectarRutasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDetectarRutasActionPerformed
    {//GEN-HEADEREND:event_btnDetectarRutasActionPerformed
        ConceptManager cm = new ConceptManager("remote:localhost/PPR", "admin", "admin");
        Concepto concepto_inicial = cm.getConceptoByName(respuesta.getPrimerConceptoAsString());
        ArrayList<String> conceptos_incluidos = respuesta.getConceptosSecundariosAsString().size() > 0 ? respuesta.getConceptosSecundariosAsString() : null;
        txtLogRutas.setText(cm.buildRouteQuery(concepto_inicial, conceptos_incluidos));
        ImmutableList<Vertex> result = cm.findRoute(concepto_inicial, conceptos_incluidos);
        //chequeamos si el objeto fue creado con anterioridad
        if (gv != null) {
            // Si fue creado, cerramos el Viewer y creamos uno nuevo
            gv.closeViewer();
        }
        gv = new GraphViewer();
        gv.viewVertexList(result, null);
    }//GEN-LAST:event_btnDetectarRutasActionPerformed

    private void lstRespuestasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lstRespuestasActionPerformed
    {//GEN-HEADEREND:event_lstRespuestasActionPerformed
        // Cargar otro texto en el edit
        txtTexto.setText(lstRespuestas.getModel().getElementAt(lstRespuestas.getSelectedIndex()));
    }//GEN-LAST:event_lstRespuestasActionPerformed

    public boolean ValidarTexto(Respuesta respuesta) throws IOException {
        LangTools lt = new LangTools();
        ConceptManager cm = new ConceptManager ("remote:localhost/PPR","admin","admin");
        Respuesta p = lt.CheckRespuesta(respuesta,cm.getConceptosComplejos(),cm.getRelacionesComplejas());
        setSOUTText(p);
        if (!p.hasErrors()) {
            txtTexto1.setText(txtTexto.getText());
            txtConceptos.setText("");
        } else {
            txtTexto1.setText("");
            txtConceptos.setText("");
        }
        return !p.hasErrors();
    }

    public void setSOUTText(Respuesta respuesta) {

        // Primero borrar el log
        txtSOUT.setText("");
        ArrayList<Termino> terminos = respuesta.getTerminos();
        StringBuilder bld = new StringBuilder();
        bld.append(String.format("Cantidad de palabras: %d\n", terminos.size()));
        for (Termino termino : terminos) {
            if (termino.hasErrors()) {
                String item = String.format("Error en la palabra: %s\n  - Corrección sugerida: %s\n", termino.getNombre(), termino.getSugerenciasCorreccion());
                bld.append(item);
            }
        }
        if (!respuesta.hasErrors()) {
            bld.append("El texto NO contiene errores.");
        }

        bld.append("\n------------ TERMINOS ------------\n");
        bld.append(respuesta.getTerminosAsString(false));

        txtSOUT.setText(bld.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetectarConceptos;
    private javax.swing.JButton btnDetectarRutas;
    private javax.swing.JButton btnDividirConceptos;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnValidar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> lstRespuestas;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextArea txtConceptos;
    private javax.swing.JTextArea txtLogRutas;
    private javax.swing.JTextArea txtSOUT;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JTextArea txtTexto1;
    private javax.swing.JTextArea txtTexto2;
    // End of variables declaration//GEN-END:variables
}
