/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainjframe;

import academico.frmAdministracion;
import docente.AltaPreguntaWizard;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Martin
 */
public class frmMain extends javax.swing.JFrame
{
    /**
     * Creates new form mainForm
     */
    public frmMain()
    {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuAdministracion = new javax.swing.JMenu();
        mnuAdminConceptos = new javax.swing.JMenuItem();
        mnuAdminPreguntas = new javax.swing.JMenuItem();
        btn_estructuras = new javax.swing.JMenuItem();
        mnuEvaluacion = new javax.swing.JMenu();
        mnuRespuesta = new javax.swing.JMenuItem();
        mnuFastEval = new javax.swing.JMenuItem();
        mnuAdminAcadémica = new javax.swing.JMenu();
        mnuAdminDocenteAlumno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corrección automatizada (Prototipo Fase 1)");
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuFile.setText("File");
        mnuFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuMain.add(mnuFile);

        mnuAdministracion.setText("Administración");
        mnuAdministracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuAdminConceptos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuAdminConceptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoSmall.png"))); // NOI18N
        mnuAdminConceptos.setLabel("Conceptos");
        mnuAdminConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminConceptosActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuAdminConceptos);

        mnuAdminPreguntas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuAdminPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PreguntaNegro.png"))); // NOI18N
        mnuAdminPreguntas.setLabel("Preguntas");
        mnuAdminPreguntas.setName("mnuAdminPreguntas"); // NOI18N
        mnuAdminPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminPreguntasActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuAdminPreguntas);

        btn_estructuras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_estructuras.setText("Estructuras");
        btn_estructuras.setName("mnuAdminPreguntas"); // NOI18N
        btn_estructuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estructurasActionPerformed(evt);
            }
        });
        mnuAdministracion.add(btn_estructuras);

        mnuMain.add(mnuAdministracion);

        mnuEvaluacion.setText("Evaluación");
        mnuEvaluacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuRespuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/respuestaNegro.png"))); // NOI18N
        mnuRespuesta.setText("Evaluar una respuesta");
        mnuRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRespuestaActionPerformed(evt);
            }
        });
        mnuEvaluacion.add(mnuRespuesta);

        mnuFastEval.setText("Fast Eval");
        mnuFastEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFastEvalActionPerformed(evt);
            }
        });
        mnuEvaluacion.add(mnuFastEval);

        mnuMain.add(mnuEvaluacion);

        mnuAdminAcadémica.setText("Académico");
        mnuAdminAcadémica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuAdminDocenteAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuAdminDocenteAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CategoriasNegro.png"))); // NOI18N
        mnuAdminDocenteAlumno.setText("Administración Docentes/Alumnos");
        mnuAdminDocenteAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminDocenteAlumnoActionPerformed(evt);
            }
        });
        mnuAdminAcadémica.add(mnuAdminDocenteAlumno);

        mnuMain.add(mnuAdminAcadémica);

        setJMenuBar(mnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRespuestaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuRespuestaActionPerformed
    {//GEN-HEADEREND:event_mnuRespuestaActionPerformed
        // TODO add your handling code here:
       JFrame j = new CorreccionWizard();
       j.pack();
       j.setLocationRelativeTo(this);
       j.setVisible(true);
    }//GEN-LAST:event_mnuRespuestaActionPerformed

    private void mnuAdminDocenteAlumnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuAdminDocenteAlumnoActionPerformed
    {//GEN-HEADEREND:event_mnuAdminDocenteAlumnoActionPerformed
        // TODO add your handling code here:
       JFrame j = new frmAdministracion();
       j.pack();
       j.setLocationRelativeTo(this);
       j.setVisible(true);
    }//GEN-LAST:event_mnuAdminDocenteAlumnoActionPerformed

    private void mnuAdminConceptosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuAdminConceptosActionPerformed
    {//GEN-HEADEREND:event_mnuAdminConceptosActionPerformed
        // TODO add your handling code here:
        JFrame j = new frmAdminConceptos();
        j.pack();
        j.setLocationRelativeTo(this);
        j.setVisible(true);
    }//GEN-LAST:event_mnuAdminConceptosActionPerformed

    private void mnuAdminPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminPreguntasActionPerformed
        // TODO add your handling code here:
        JFrame j = new frmAdminPreguntas();
        j.pack();
        j.setLocationRelativeTo(this);
        j.setVisible(true);
    }//GEN-LAST:event_mnuAdminPreguntasActionPerformed

    private void mnuFastEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFastEvalActionPerformed
        // TODO add your handling code here:
       JFrame j = new frmFastEval();
       j.pack();
       j.setLocationRelativeTo(this);
       j.setVisible(true);
    }//GEN-LAST:event_mnuFastEvalActionPerformed

    private void btn_estructurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estructurasActionPerformed
        // TODO add your handling code here:
        JFrame j = new frmAdminEstructuras();
        j.pack();
        j.setLocationRelativeTo(this);
        j.setVisible(true);

    }//GEN-LAST:event_btn_estructurasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            */
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_estructuras;
    private javax.swing.JMenu mnuAdminAcadémica;
    private javax.swing.JMenuItem mnuAdminConceptos;
    private javax.swing.JMenuItem mnuAdminDocenteAlumno;
    private javax.swing.JMenuItem mnuAdminPreguntas;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuEvaluacion;
    private javax.swing.JMenuItem mnuFastEval;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JMenuItem mnuRespuesta;
    // End of variables declaration//GEN-END:variables
}
