FROM openjdk:8-alpine

MAINTAINER Martin Casatti (mcasatti@gmail.com)

COPY ./software/java/build/libs/sibila-0.7-dev.jar ./sibilar.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "sibilar.jar"]

#CMD ["java", "-jar", "sibilar.jar"]