version: '3.7'
services:
  orientdb:
    image: 'mcasatti/sibila-orientdb:latest'
    container_name: sibila-orientdb
    restart: always
    volumes:
      - 'orientdb_data:/var/lib/orientdb/data'
    ports:
      - '2424:2424'
      - '2480:2480'
    environment:
      - ORIENTDB_OPTS_MEMORY=-Xmx512m
    networks:
      sibila_net:
        ipv4_address: 172.28.1.1
  spacy:
    image: 'mcasatti/sibila-spacy:latest'
    container_name: sibila-spacy
    restart: always
    ports:
      - '5000:5000'
    networks:
      sibila_net:
        ipv4_address: 172.28.1.2
  sibila:
    image: 'mcasatti/sibila-java:latest'
    container_name: sibila-java
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SIBILA_ORIENT_HOST=172.28.1.1
      - SIBILA_SPACY_HOST=http://172.28.1.2
    depends_on:
      - orientdb
      - spacy
    networks:
      sibila_net:
        ipv4_address: 172.28.1.3
volumes:
  orientdb_data: {}
networks:
  sibila_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
