/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academico;

import javax.swing.DefaultListModel;

/**
 *
 * @author Martin
 */
public class frmAdministracion extends javax.swing.JFrame
{

    DocentesManager mDocentes;
    AlumnosManager mAlumnos;
    
    /**
     * Creates new form frmAdministracion
     */
    public frmAdministracion()
    {
        initComponents();
        mDocentes = new DocentesManager ("remote:localhost/PPR","admin","admin");
        mAlumnos = new AlumnosManager ("remote:localhost/PPR","admin","admin");
        
        LoadDocentes();
        LoadAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        edtNomDocente = new javax.swing.JTextField();
        edtApeDocente = new javax.swing.JTextField();
        edtLegDocente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddDocente = new javax.swing.JButton();
        btnDelDocente = new javax.swing.JButton();
        btnUpdDocente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDocentes = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtNomAlumno = new javax.swing.JTextField();
        edtApeAlumno = new javax.swing.JTextField();
        edtLegAlumno = new javax.swing.JTextField();
        btnAddAlumno = new javax.swing.JButton();
        btnDelAlumno = new javax.swing.JButton();
        btnUpdAlumno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlumnos = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        cmbCondicion = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Modelo Relacional Simulado");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Docente"));

        jLabel1.setText("Nom.:");

        jLabel2.setText("Ape:");

        jLabel3.setText("Leg:");

        btnAddDocente.setText("Agregar");
        btnAddDocente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddDocenteActionPerformed(evt);
            }
        });

        btnDelDocente.setText("Borrar");
        btnDelDocente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDelDocenteActionPerformed(evt);
            }
        });

        btnUpdDocente.setText("Modificar");
        btnUpdDocente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdDocenteActionPerformed(evt);
            }
        });

        lstDocentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstDocentes);

        jLabel8.setText("Usar el id del nodo en el campo legajo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtNomDocente)
                            .addComponent(edtApeDocente)
                            .addComponent(edtLegDocente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNomDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtApeDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtLegDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelDocente)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumno"));

        jLabel4.setText("Nom.:");

        jLabel5.setText("Ape:");

        jLabel6.setText("Leg:");

        btnAddAlumno.setText("Agregar");
        btnAddAlumno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddAlumnoActionPerformed(evt);
            }
        });

        btnDelAlumno.setText("Borrar");
        btnDelAlumno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDelAlumnoActionPerformed(evt);
            }
        });

        btnUpdAlumno.setText("Modificar");
        btnUpdAlumno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdAlumnoActionPerformed(evt);
            }
        });

        lstAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstAlumnos);

        jLabel7.setText("Cond:");

        cmbCondicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R", "L", "P" }));

        jLabel10.setText("Usar el id del nodo en el campo legajo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtNomAlumno)
                            .addComponent(edtApeAlumno)
                            .addComponent(edtLegAlumno)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNomAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtApeAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtLegAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAlumno)
                    .addComponent(jLabel7)
                    .addComponent(cmbCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelAlumno)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadDocentes()
    {
            DefaultListModel lstModel = new DefaultListModel();
            for (Docente d : mDocentes.getDocentes())
            {
                lstModel.addElement("["+d.IdNodo+"]  "+d.Nombre+" "+d.Apellido+", "+d.Legajo);
            }
            lstDocentes.setModel(lstModel);
    }
    
    private void LoadAlumnos()
    {
            DefaultListModel lstModel = new DefaultListModel();
            for (Alumno d : mAlumnos.getAlumnos())
            {
                lstModel.addElement("["+d.IdNodo+"]  "+d.Nombre+" "+d.Apellido+", "+d.Legajo+" : "+d.Condicion);
            }
            lstAlumnos.setModel(lstModel);
    }
    
    
    private void btnAddDocenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddDocenteActionPerformed
    {//GEN-HEADEREND:event_btnAddDocenteActionPerformed
        // Agregar un docente
        Docente d = new Docente()
        {
            {
                Nombre = edtNomDocente.getText();
                Apellido = edtApeDocente.getText();
                Legajo = edtLegDocente.getText();
            }
        };
        mDocentes.addDocente(d);
        LoadDocentes();
    }//GEN-LAST:event_btnAddDocenteActionPerformed

    private void btnAddAlumnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddAlumnoActionPerformed
    {//GEN-HEADEREND:event_btnAddAlumnoActionPerformed
        // Agregar un alumno
        Alumno d = new Alumno()
        {
            {
                Nombre = edtNomAlumno.getText();
                Apellido = edtApeAlumno.getText();
                Legajo = edtLegAlumno.getText();
                Condicion = cmbCondicion.getSelectedItem().toString();
            }
        };
        mAlumnos.addAlumno(d);
        LoadAlumnos();
    }//GEN-LAST:event_btnAddAlumnoActionPerformed

    private void btnDelDocenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDelDocenteActionPerformed
    {//GEN-HEADEREND:event_btnDelDocenteActionPerformed
        // Borrar un docente
        Docente d = mDocentes.getDocenteByLegajo(edtLegDocente.getText());
        if (d != null)
        {
            mDocentes.delDocente(d);
            LoadDocentes();
        }
    }//GEN-LAST:event_btnDelDocenteActionPerformed

    private void btnDelAlumnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDelAlumnoActionPerformed
    {//GEN-HEADEREND:event_btnDelAlumnoActionPerformed
        // Borrar un alumno
        Alumno d = mAlumnos.getAlumnoByLegajo(edtLegAlumno.getText());
        if (d != null)
        {
            mAlumnos.delAlumno(d);
            LoadAlumnos();
        }
    }//GEN-LAST:event_btnDelAlumnoActionPerformed

    private void btnUpdDocenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdDocenteActionPerformed
    {//GEN-HEADEREND:event_btnUpdDocenteActionPerformed
        Docente old = mDocentes.getDocenteByLegajo(edtLegDocente.getText());
        Docente d = new Docente()
        {
            {
                Nombre = edtNomDocente.getText();
                Apellido = edtApeDocente.getText();
                Legajo = edtLegDocente.getText();
            }
        };
        
        if (old != null)
        {
            mDocentes.updDocente(old, d);
        }
        LoadDocentes();
    }//GEN-LAST:event_btnUpdDocenteActionPerformed

    private void btnUpdAlumnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdAlumnoActionPerformed
    {//GEN-HEADEREND:event_btnUpdAlumnoActionPerformed
        Alumno old = mAlumnos.getAlumnoByLegajo(edtLegAlumno.getText());
        Alumno d = new Alumno()
        {
            {
                Nombre = edtNomAlumno.getText();
                Apellido = edtApeAlumno.getText();
                Legajo = edtLegAlumno.getText();
                Condicion = cmbCondicion.getSelectedItem().toString();
            }
        };
        
        if (old != null)
        {
            mAlumnos.updAlumno(old, d);
        }
        LoadAlumnos();
    }//GEN-LAST:event_btnUpdAlumnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAlumno;
    private javax.swing.JButton btnAddDocente;
    private javax.swing.JButton btnDelAlumno;
    private javax.swing.JButton btnDelDocente;
    private javax.swing.JButton btnUpdAlumno;
    private javax.swing.JButton btnUpdDocente;
    private javax.swing.JComboBox cmbCondicion;
    private javax.swing.JTextField edtApeAlumno;
    private javax.swing.JTextField edtApeDocente;
    private javax.swing.JTextField edtLegAlumno;
    private javax.swing.JTextField edtLegDocente;
    private javax.swing.JTextField edtNomAlumno;
    private javax.swing.JTextField edtNomDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstAlumnos;
    private javax.swing.JList lstDocentes;
    // End of variables declaration//GEN-END:variables
}
